version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: vartur_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-vartur_task}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: vartur_app
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    environment:
      DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD:-root}@mysql:3306/${MYSQL_DATABASE:-vartur_task}
      NODE_ENV: production
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./public/uploads:/app/public/uploads

volumes:
  mysql_data: 